collections:
  letters:
    output: true
    permalink: /letters/:title/
    future: true  # 允許顯示未來的信件

defaults:
  - scope:
      path: "letters"
      type: letters
    values:
      layout: letter
